image: node # change to match your node version

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

build:
  stage: build
  script:
    - CI=false npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
      
deploy:
  stage: deploy
  image: instrumentisto/rsync-ssh
  script:
    - KEYFILE=`mktemp`
    - echo ${DEPLOY_KEY} > $KEYFILE
    - chmod 600 $KEYFILE
    - rsync -avz -e "ssh -i $KEYFILE -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222" public web@vaporwave.derphost.com:/home/web/vanderpot.com/resume
    - rm $KEYFILE
  only:
    - master # run on master branch
  dependencies:
    - build