name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      branch_name: ${{ steps.branch-name.outputs.current_branch }}

    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6.5
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '20'
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.SHA }}

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-22.04
    if: needs.build.outputs.branch_name == 'master'
    needs: build
    concurrency: production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build

  screenshot:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: "Take Screenshots"
        run: |-
          set -x
          mkdir webroot
          mv build webroot/resume
          yarn serve webroot &
          set +x
          while ! curl --output /dev/null --silent --head --fail http://127.0.0.1:3000/; do sleep 0.1 && echo -n .; done;
          set -x
          yarn screenshot
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshot-*.png

  compare-screenshot:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    needs:
      - build
      - screenshot
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-sc
          restore-keys: |
            ${{ runner.os }}-yarn-sc
      - uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: ours
      - uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: main.yml
          name: screenshots
          branch: ${{github.event.pull_request.base.ref}}
          search_artifacts: true
          path: theirs
      - run: ls -R ours theirs
      - run: |-
          yarn add pixelmatch
          mkdir out
          echo "## Visual Diff" >> comment-body.txt
          for file in ours/*; do 
            name=`basename $file`
            echo "### $name" >> comment-body.txt
            echo '```' >> comment-body.txt 
            yarn -s pixelmatch ours/$name theirs/$name out/$name 0.1 >> comment-body.txt
            echo '```' >> comment-body.txt
          done
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot-diff
          path: out/*.png

      - id: get-comment-body
        run: |
          body="$(cat comment-body.txt)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Visual Diff

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
