name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.SHA }}

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-18.04
    if: needs.build.outputs.branch_name == 'master'
    needs: build
    concurrency: production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build

  screenshot:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - run: |-
          pwd
          mkdir webroot
          mv build webroot/resume
          ls -R webroot
          yarn screenshot:ci
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshot-*.png

  compare-screenshot:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    needs:
      - build
      - screenshot
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ours
      - name: Display structure of our files
        run: ls -R ours
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: Build
          branch: ${{github.base_ref}}
          path: theirs
      - name: Display structure of target files
        run: ls -R theirs
