name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.SHA }}

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-18.04
    if: needs.build.outputs.branch_name == 'master'
    needs: build
    concurrency: production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build

  screenshot:
    runs-on: ubuntu-18.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: "Take Screenshots"
        run: |-
          set -x
          mkdir webroot
          mv build webroot/resume
          yarn serve -s webroot &
          set +x
          while ! curl --output /dev/null --silent --head --fail http://127.0.0.1:3000/; do sleep 0.1 && echo -n .; done;
          set -x
          yarn screenshot
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshot-*.png

  compare-screenshot:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    needs:
      - build
      - screenshot
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '17'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-sc
          restore-keys: |
            ${{ runner.os }}-yarn-sc
      - uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: ours
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: main.yml
          name: screenshots
          branch: ${{github.event.pull_request.base.ref}}
          search_artifacts: true
          path: theirs
      - run: ls -R ours theirs
      - run: |-
          yarn add pixelmatch
          mkdir out
          for file in ours/*; do 
            name=`basename $file`
            yarn pixelmatch ours/$name theirs/$name out/$name 0.1
          done
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot-diff
          path: out/*.png