name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    outputs:
      commit_hash: ${{ steps.save-commit-hash.outputs.commit_hash }}
      branch_name: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          REACT_APP_GIT_SHA: ${{ github.SHA }}

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-18.04
    if: needs.build.outputs.branch_name == 'master'
    needs: build
    concurrency: production
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build

  screenshot:
    runs-on: ubuntu-18.04
    needs: build
    strategy:
      matrix:
        width: [ 1200, 992, 768, 600 ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: mkdir screenshots
      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://github.com/swinton/screenshot-website
          destination: screenshot-${{ matrix.width }}.png
          width: ${{ matrix.width }}

  compare-screenshot:
    runs-on: ubuntu-18.04
    if: github.event_name == 'pull_request'
    needs:
      - build
      - screenshot
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
          path: ours
      - name: Display structure of our files
        run: ls -R
        working-directory: ours
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: main.yml
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
          path: theirs
      - name: Display structure of target files
        run: ls -R
        working-directory: theirs
